# Generated by Django 4.2.1 on 2023-06-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='benefits',
            new_name='pack_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='other_info',
        ),
        migrations.AddField(
            model_name='product',
            name='brands',
            field=models.TextField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=100),
        ),
    ]
